name: Compile and upload MacOS binaries
on:
  workflow_dispatch:

jobs:

  mac:
    strategy:
      fail-fast: false
      matrix:
        arch: [x86, arm64]
    runs-on: ${{ matrix.arch == 'x86' && 'macos-13' || 'macos-latest' }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 16

    - name: Use Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable

    - name: Build module
      env:
        MACOSX_DEPLOYMENT_TARGET: 10.13
      run: |
        npm ci --ignore-scripts
        npm run build -- --release --features metal,window

    - name: Package module
      run: |
        npm test && npm run package

    - name: Upload
      env:
        NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
      run: |
        npm run upload
