name: Run tests
on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    name: Rebuild & Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - windows-latest
          - ubuntu-latest
        node:
          - 16
          - 22

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Use Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable

    # temporarily necessary while skia_bindings 0.78.2 is looking for the `pipes` module which
    # was renamed in Python 3.13 (can hopefully be removed at the next release…)
    - name: Downgrade Python (depot_tools workaround)
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Build for Mac
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        npm ci --ignore-scripts
        npm run build -- --release --features metal,window

    - name: Build for Linux
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        npm ci --ignore-scripts
        npm run build -- --release --features vulkan,window,skia-safe/embed-freetype,skia-safe/freetype-woff2
    
    - name: Build for Windows
      if: ${{ matrix.os == 'windows-latest' }}
      shell: bash
      run: |
        npm ci --ignore-scripts
        npm run build -- --release --features vulkan,window

    - name: Run tests
      run: |
        npm test --verbose
        ls -l lib/v6/index.node

